### ISSUE TITLE
Can't build the examples

### ISSUE THREAD

**Issue by BartAdv** [dylanede/embed_js#1]
```
$ cd examples/strings
$ cargo make
```

```
[cargo-make] INFO - cargo-make 0.8.0
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Setting Up Env.
[cargo-make] INFO - Running Task: init
[cargo-make] INFO - Running Task: pre-format
[cargo-make] INFO - Running Task: format-stable
[cargo-make] INFO - Running Task: format-nightly
[cargo-make] INFO - Execute Command: "cargo" "fmt" "--" "--write-mode=overwrite"
[cargo-make] INFO - Running Task: post-format
[cargo-make] INFO - Running Task: format-flow
[cargo-make] INFO - Running Task: pre-build
[cargo-make] INFO - Running Task: build
[cargo-make] INFO - Execute Command: "cargo" "build" "--target=wasm32-unknown-unknown" "--release"
    Finished release [optimized] target(s) in 0.0 secs
[cargo-make] INFO - Running Task: post-build
[cargo-make] INFO - Execute Command: "cargo" "script" "post_build.rs"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:916:4
stack backtrace:
   0:     0x5607226c572b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hf105f7af69c127bc
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x5607226c049e - std::sys_common::backtrace::print::h09b6b617d6794ae7
                               at /checkout/src/libstd/sys_common/backtrace.rs:68
                               at /checkout/src/libstd/sys_common/backtrace.rs:57
   2:     0x5607226c7ad0 - std::panicking::default_hook::{{closure}}::h54b87f82ac2f6b70
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x5607226c7827 - std::panicking::default_hook::h0d10433ace2bd41b
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x5607226c7e3b - std::panicking::rust_panic_with_hook::heab159b2add93769
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x5607226c7c8e - std::panicking::begin_panic::h03333c2d39ce28db
                               at /checkout/src/libstd/panicking.rs:538
   6:     0x5607226c7bfa - std::panicking::begin_panic_fmt::h3526e57f9f07757f
                               at /checkout/src/libstd/panicking.rs:522
   7:     0x5607226c7b92 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:498
   8:     0x5607227144e0 - core::panicking::panic_fmt::hf33f5585ac637ed8
                               at /checkout/src/libcore/panicking.rs:71
   9:     0x56072268a073 - core::result::unwrap_failed::h138d5bb17be7a6c9
  10:     0x5607226baacd - embed_js_build::postprocess_crate::h41ea60ec92eb9fe4
  11:     0x56072267a1ab - post_build::main::hfaf075fb3f0dda65
  12:     0x5607226d87ee - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:101
  13:     0x5607226c5513 - std::rt::lang_start::hf5cab955c8fc1b8d
                               at /checkout/src/libstd/panicking.rs:459
                               at /checkout/src/libstd/rt.rs:58
  14:     0x7fed242dbf69 - __libc_start_main
  15:     0x5607226796e9 - _start
  16:                0x0 - <unknown>
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.
```

It's somewhat hard to determine what's going on (I'm newcomer when it comes to Rust/cargo-make/cargo-script), but I've found out that following:

```
let bin_prefix = target_directory.join(&format!("wasm32-unknown-unknown/{}/{}", if debug { "debug" } else { "release" }, lib_name));
```

gives path to `wasm32-unknown-unknown/release/strings`, which just doesn't exist.

**Comment by dylanede** [comment]
`bin_prefix` is not accessed directly - it's used to build `wasm_path` and `d_path`, with the extensions ".wasm" and ".d" respectively. Do either of these files ("strings.wasm" and "strings.d") not exist in target/wasm32-unknown-unknown/release? Or is that directory wrong as well? What platform are you on, and could you give me the output of `rustup show` and `rustup component list`?

**Comment by dylanede** [comment]
Ah, I think I know what the problem is - I forgot to mention the dependency on [wasm-gc](https://github.com/alexcrichton/wasm-gc), which also needs to be installed via cargo install (see the wasm-gc readme for details).

I'll update the readme to mention this, but I'll wait to see if this fixes things for you before closing.

**Comment by sagiegurari** [comment]
You can add it to the Makefile.toml in an init task.

**Comment by BartAdv** [comment]
Oh yes, it now works.

And indeed, the files you've mentioned were there, no idea why I haven't spotted them earlier.

And damn (though this is unrelated to this repo), the failure messages from build scripts aren't really helpful  :D

**Comment by dylanede** [comment]
Actually, I think it is related. Work could be done in embed_js_build to make the error messages better in cases like these. I just haven't put time into that yet.
